version: '3'
services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: weatheruser
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
